// Game Configuration - Metadata for all 100 games
// This file contains the game catalog with icons, descriptions, and categories

const GAMES_CATALOG = [
  // Arcade Games (1-20)
  { id: 1, name: 'Snake', icon: '🐍', category: 'arcade', description: 'Classic snake game', implemented: true },
  { id: 2, name: 'Flappy Bird', icon: '🐦', category: 'arcade', description: 'Tap to fly through pipes', implemented: false },
  { id: 3, name: 'Brick Breaker', icon: '🧱', category: 'arcade', description: 'Break all the bricks', implemented: false },
  { id: 4, name: 'Pong', icon: '🏓', category: 'arcade', description: 'Classic paddle game', implemented: false },
  { id: 5, name: 'Space Invaders', icon: '👾', category: 'arcade', description: 'Defend against aliens', implemented: false },
  { id: 6, name: 'Pac-Man Mini', icon: '👻', category: 'arcade', description: 'Collect dots, avoid ghosts', implemented: false },
  { id: 7, name: 'Frogger', icon: '🐸', category: 'arcade', description: 'Cross the road safely', implemented: false },
  { id: 8, name: 'Asteroids', icon: '☄️', category: 'arcade', description: 'Destroy asteroids', implemented: false },
  { id: 9, name: 'Helicopter', icon: '🚁', category: 'arcade', description: 'Navigate through caves', implemented: false },
  { id: 10, name: 'Runner', icon: '🏃', category: 'arcade', description: 'Endless runner game', implemented: false },
  { id: 11, name: 'Missile Command', icon: '🚀', category: 'arcade', description: 'Defend your cities', implemented: false },
  { id: 12, name: 'Galaga Mini', icon: '🛸', category: 'arcade', description: 'Space shooter', implemented: false },
  { id: 13, name: 'Platformer', icon: '🎮', category: 'arcade', description: 'Jump and run', implemented: false },
  { id: 14, name: 'Bubble Shooter', icon: '🫧', category: 'arcade', description: 'Match and pop bubbles', implemented: false },
  { id: 15, name: 'Worm', icon: '🪱', category: 'arcade', description: 'Grow your worm', implemented: false },
  { id: 16, name: 'Tank Battle', icon: '🎯', category: 'arcade', description: 'Tank vs tank', implemented: false },
  { id: 17, name: 'Catch Game', icon: '🎪', category: 'arcade', description: 'Catch falling items', implemented: false },
  { id: 18, name: 'Avoid', icon: '⚡', category: 'arcade', description: 'Avoid obstacles', implemented: false },
  { id: 19, name: 'Drift Racer', icon: '🏎️', category: 'arcade', description: 'Racing game', implemented: false },
  { id: 20, name: 'Jumper', icon: '⬆️', category: 'arcade', description: 'Jump as high as you can', implemented: false },

  // Puzzle Games (21-40)
  { id: 21, name: 'Tic Tac Toe', icon: '⭕', category: 'puzzle', description: 'Classic X and O game', implemented: true },
  { id: 22, name: 'Memory Match', icon: '🃏', category: 'puzzle', description: 'Match pairs of cards', implemented: true },
  { id: 23, name: 'Sudoku', icon: '🔢', category: 'puzzle', description: 'Number puzzle', implemented: false },
  { id: 24, name: '2048', icon: '🔲', category: 'puzzle', description: 'Combine numbers', implemented: false },
  { id: 25, name: 'Sliding Puzzle', icon: '🧩', category: 'puzzle', description: 'Arrange the tiles', implemented: false },
  { id: 26, name: 'Mahjong', icon: '🀄', category: 'puzzle', description: 'Match mahjong tiles', implemented: false },
  { id: 27, name: 'Crossword Mini', icon: '📝', category: 'puzzle', description: 'Word puzzle', implemented: false },
  { id: 28, name: 'Minesweeper', icon: '💣', category: 'puzzle', description: 'Find all mines', implemented: false },
  { id: 29, name: 'Jigsaw', icon: '🧩', category: 'puzzle', description: 'Complete the picture', implemented: false },
  { id: 30, name: 'Rubik Cube 2D', icon: '🎨', category: 'puzzle', description: 'Color matching', implemented: false },
  { id: 31, name: 'Match Three', icon: '💎', category: 'puzzle', description: 'Match 3 gems', implemented: false },
  { id: 32, name: 'Dots Connect', icon: '⚫', category: 'puzzle', description: 'Connect the dots', implemented: false },
  { id: 33, name: 'Flow Free', icon: '🌊', category: 'puzzle', description: 'Connect colors', implemented: false },
  { id: 34, name: 'Nonogram', icon: '⬛', category: 'puzzle', description: 'Picture logic puzzle', implemented: false },
  { id: 35, name: 'Tangram', icon: '🔺', category: 'puzzle', description: 'Shape puzzle', implemented: false },
  { id: 36, name: 'Word Search', icon: '🔍', category: 'puzzle', description: 'Find hidden words', implemented: false },
  { id: 37, name: 'Unblock', icon: '🚗', category: 'puzzle', description: 'Slide blocks to exit', implemented: false },
  { id: 38, name: 'Lights Out', icon: '💡', category: 'puzzle', description: 'Turn off all lights', implemented: false },
  { id: 39, name: 'Simon Says', icon: '🎵', category: 'puzzle', description: 'Memory sequence game', implemented: false },
  { id: 40, name: 'Number Chain', icon: '🔗', category: 'puzzle', description: 'Connect numbers', implemented: false },

  // Strategy Games (41-55)
  { id: 41, name: 'Chess Mini', icon: '♟️', category: 'strategy', description: 'Classic chess', implemented: false },
  { id: 42, name: 'Checkers', icon: '⚫', category: 'strategy', description: 'Board game', implemented: false },
  { id: 43, name: 'Connect Four', icon: '🔴', category: 'strategy', description: 'Connect 4 in a row', implemented: false },
  { id: 44, name: 'Reversi', icon: '⚪', category: 'strategy', description: 'Flip the pieces', implemented: false },
  { id: 45, name: 'Tower Defense', icon: '🗼', category: 'strategy', description: 'Defend your base', implemented: false },
  { id: 46, name: 'Battleship', icon: '🚢', category: 'strategy', description: 'Sink enemy ships', implemented: false },
  { id: 47, name: 'Go Mini', icon: '⚫', category: 'strategy', description: 'Ancient board game', implemented: false },
  { id: 48, name: 'Risk Dice', icon: '🎲', category: 'strategy', description: 'Dice battle game', implemented: false },
  { id: 49, name: 'Card War', icon: '🎴', category: 'strategy', description: 'Higher card wins', implemented: false },
  { id: 50, name: 'Dots & Boxes', icon: '📦', category: 'strategy', description: 'Complete squares', implemented: false },
  { id: 51, name: 'Nim', icon: '🪵', category: 'strategy', description: 'Mathematical game', implemented: false },
  { id: 52, name: 'Mill', icon: '⭕', category: 'strategy', description: "Nine men's morris", implemented: false },
  { id: 53, name: 'Mastermind', icon: '🎯', category: 'strategy', description: 'Code breaking game', implemented: false },
  { id: 54, name: 'Gomoku', icon: '⚫', category: 'strategy', description: 'Five in a row', implemented: false },
  { id: 55, name: 'Hex', icon: '⬡', category: 'strategy', description: 'Connect opposite sides', implemented: false },

  // Casual Games (56-75)
  { id: 56, name: 'Whack-a-Mole', icon: '🔨', category: 'casual', description: 'Hit the moles', implemented: true },
  { id: 57, name: 'Cookie Clicker', icon: '🍪', category: 'casual', description: 'Click to bake cookies', implemented: false },
  { id: 58, name: 'Reaction Time', icon: '⏱️', category: 'casual', description: 'Test your reflexes', implemented: true },
  { id: 59, name: 'Color Match', icon: '🎨', category: 'casual', description: 'Match the color', implemented: true },
  { id: 60, name: 'Speed Click', icon: '👆', category: 'casual', description: 'Click as fast as you can', implemented: false },
  { id: 61, name: 'Ball Drop', icon: '⚽', category: 'casual', description: 'Drop balls in buckets', implemented: false },
  { id: 62, name: 'Peg Solitaire', icon: '🔵', category: 'casual', description: 'Jump and remove pegs', implemented: false },
  { id: 63, name: 'Hangman', icon: '📝', category: 'casual', description: 'Guess the word', implemented: false },
  { id: 64, name: 'Doodle Jump', icon: '🦘', category: 'casual', description: 'Jump to platforms', implemented: false },
  { id: 65, name: 'Slither', icon: '🐍', category: 'casual', description: 'Grow and avoid', implemented: false },
  { id: 66, name: 'Tap Tap', icon: '👇', category: 'casual', description: 'Tap at the right time', implemented: false },
  { id: 67, name: 'Spin Wheel', icon: '🎡', category: 'casual', description: 'Spin and win', implemented: false },
  { id: 68, name: 'Paper Toss', icon: '🗑️', category: 'casual', description: 'Toss paper in bin', implemented: false },
  { id: 69, name: 'Stack Tower', icon: '🏗️', category: 'casual', description: 'Stack blocks high', implemented: false },
  { id: 70, name: 'Balance', icon: '⚖️', category: 'casual', description: 'Balance objects', implemented: false },
  { id: 71, name: 'Aim Trainer', icon: '🎯', category: 'casual', description: 'Click the targets', implemented: false },
  { id: 72, name: 'Roll Ball', icon: '⚾', category: 'casual', description: 'Roll to the goal', implemented: false },
  { id: 73, name: 'Drawing Pad', icon: '🎨', category: 'casual', description: 'Free drawing', implemented: false },
  { id: 74, name: 'Piano Tiles', icon: '🎹', category: 'casual', description: 'Tap black tiles', implemented: false },
  { id: 75, name: 'Color Fill', icon: '🖌️', category: 'casual', description: 'Fill the grid', implemented: false },

  // Trivia & Word Games (76-90)
  { id: 76, name: 'Trivia Quiz', icon: '❓', category: 'trivia', description: 'Test your knowledge', implemented: false },
  { id: 77, name: 'Math Quiz', icon: '➕', category: 'trivia', description: 'Solve math problems', implemented: true },
  { id: 78, name: 'Geography Quiz', icon: '🌍', category: 'trivia', description: 'World capitals quiz', implemented: false },
  { id: 79, name: 'Flag Quiz', icon: '🚩', category: 'trivia', description: 'Guess the flag', implemented: false },
  { id: 80, name: 'Anagram', icon: '🔤', category: 'trivia', description: 'Unscramble words', implemented: false },
  { id: 81, name: 'Spelling Bee', icon: '🐝', category: 'trivia', description: 'Spell correctly', implemented: false },
  { id: 82, name: 'Type Racer', icon: '⌨️', category: 'trivia', description: 'Typing speed test', implemented: false },
  { id: 83, name: 'True or False', icon: '✓', category: 'trivia', description: 'True/false questions', implemented: false },
  { id: 84, name: 'Riddles', icon: '🤔', category: 'trivia', description: 'Solve riddles', implemented: false },
  { id: 85, name: 'Word Ladder', icon: '🪜', category: 'trivia', description: 'Change one letter', implemented: false },
  { id: 86, name: 'Vocabulary', icon: '📚', category: 'trivia', description: 'Word meanings', implemented: false },
  { id: 87, name: 'Logo Quiz', icon: '🏢', category: 'trivia', description: 'Guess the brand', implemented: false },
  { id: 88, name: 'Movie Quiz', icon: '🎬', category: 'trivia', description: 'Name the movie', implemented: false },
  { id: 89, name: 'Music Quiz', icon: '🎵', category: 'trivia', description: 'Name the song', implemented: false },
  { id: 90, name: 'Science Quiz', icon: '🔬', category: 'trivia', description: 'Science questions', implemented: false },

  // Extra Games (91-100)
  { id: 91, name: 'Dice Roll', icon: '🎲', category: 'casual', description: 'Roll the dice', implemented: false },
  { id: 92, name: 'Coin Flip', icon: '🪙', category: 'casual', description: 'Flip a coin', implemented: true },
  { id: 93, name: 'Rock Paper Scissors', icon: '✂️', category: 'casual', description: 'Beat the computer', implemented: true },
  { id: 94, name: 'Number Guess', icon: '🔢', category: 'casual', description: 'Guess the number', implemented: true },
  { id: 95, name: 'Lottery', icon: '🎰', category: 'casual', description: 'Pick lucky numbers', implemented: false },
  { id: 96, name: 'Scratch Card', icon: '🎫', category: 'casual', description: 'Scratch to win', implemented: false },
  { id: 97, name: 'Slot Machine', icon: '🎰', category: 'casual', description: 'Spin to win', implemented: false },
  { id: 98, name: 'Bingo', icon: '🅱️', category: 'casual', description: 'Mark your card', implemented: false },
  { id: 99, name: 'Dominoes', icon: '🁢', category: 'strategy', description: 'Match the dots', implemented: false },
  { id: 100, name: 'Solitaire', icon: '🂡', category: 'strategy', description: 'Card solitaire', implemented: false }
];
